### ISSUE TITLE
 SHDLC device returned error code 33: Unknown error with 

### ISSUE THREAD

**Issue by martijnschouten** [Sensirion/python-uart-scc1#6]
Hi,

I got the SLF3S-1300F Evaluation Kit from Mouser. I connected the sensor to my computer using the supplied USB to i2c converter. I installed the sensirion-uart-scc1 package in my virtual environment and made a file "sensiron_flow_sensor_test.py" with the contents of "contscc1_slf3x_example.py". However, if I run this example I get error 33, see the terminal output below. Any idea what could be the issue?

I am running python 3.11.1 on windows 11.

Kind regards,

Martijn Schouten

```
(venv) D:\lmts\git\pumptestbench_v2>python ./devices/flow_sensor/sensirion_flow_sensor_test.py --serial-port COM12
SHDLC device with address 0 returned error 33.
Traceback (most recent call last):
  File "D:\lmts\git\pumptestbench_v2\venv\Lib\site-packages\sensirion_shdlc_driver\device_base.py", line 88, in execute
    data, err = self._connection.execute(self._slave_address, command)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lmts\git\pumptestbench_v2\venv\Lib\site-packages\sensirion_shdlc_driver\connection.py", line 68, in execute
    data, error = self.transceive(slave_address, command.id, command.data,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lmts\git\pumptestbench_v2\venv\Lib\site-packages\sensirion_shdlc_driver\connection.py", line 105, in transceive
    raise ShdlcDeviceError(error_code)  # Command failed to execute
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sensirion_shdlc_driver.errors.ShdlcDeviceError: SHDLC device returned error code 33: Unknown error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\lmts\git\pumptestbench_v2\devices\flow_sensor\sensirion_flow_sensor_test.py", line 15, in <module>
    sensor = Scc1Slf3x(device)
             ^^^^^^^^^^^^^^^^^
  File "D:\lmts\git\pumptestbench_v2\venv\Lib\site-packages\sensirion_uart_scc1\drivers\scc1_slf3x.py", line 32, in __init__
    self._serial_number, self._product_id = self._get_serial_number_and_product_id()
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lmts\git\pumptestbench_v2\venv\Lib\site-packages\sensirion_uart_scc1\drivers\scc1_slf3x.py", line 202, in _get_serial_number_and_product_id
    data = self._scc1.transceive(0x50, [], 0.01)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lmts\git\pumptestbench_v2\venv\Lib\site-packages\sensirion_uart_scc1\scc1_shdlc_device.py", line 64, in transceive
    result = self.execute(ShdlcCommand(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\lmts\git\pumptestbench_v2\venv\Lib\site-packages\sensirion_shdlc_driver\device_base.py", line 93, in execute
    raise self._get_device_error(exc.error_code)
sensirion_shdlc_driver.errors.ShdlcDeviceError: SHDLC device returned error code 33: Unknown error.
```

**Comment by martijnschouten** [comment]
I verified with the viewer software that the sensor itself is working, a screenshot can be found below.

![viewer software](https://github.com/Sensirion/python-uart-scc1/assets/6079002/e503acc6-608a-4bc3-becc-aa8431a220fe)

**Comment by martijnschouten** [comment]
After testing flow sensor with the viewer software the demo software suddenly also works. So the problem seems to be that you just have to run it in the viewer software once

**Comment by martijnschouten** [comment]
Hello @qfisch,

Thank you very much for picking this up and good to hear the issue is repeatable. I'm looking forward for the patch.

Kind regards,

Martijn

**Comment by qfisch** [comment]
Hej @martijnschouten 
It is in the planning for the coming week.

Best
Q

**Comment by psachs** [comment]
@martijnschouten 

The latest version 1.1.0 is release on pypi and supports setting the correct sensor type on the cable. The examples are also updated.

Best regards,
Pascal

**Comment by martijnschouten** [comment]
Hi Pascal,

Thank you so much, that commit solved the issue.🥳

Kind regards,

Martijn
